### ISSUE TITLE
spfile naming for RAC instances

### ISSUE THREAD

**Issue by mikealbert** [CruGlobal/ansible-oracle-db-upgrade#1]
@davidhollenberger Does this line need to account for the naming differences for RAC vs single instance?

https://github.com/CruGlobal/ansible-oracle-db-upgrade/blob/master/tasks/upgrade.yml#L55

```
- name: copy spfile file to new home
  shell: "cp {{ oracle_home_old }}/dbs/spfile{{ db_name }}.ora {{ oracle_home }}/dbs/"
```

**Comment by davidhollenberger** [comment]
Yes.  I haven't really started on the RAC specific steps.  So there's probably a few things that need to be accounted for with RAC db upgrades.

**Comment by mikealbert** [comment]
Ah ok.  I'll just look for single instance stuff for now then.
