### ISSUE TITLE
Save script output?

### ISSUE THREAD

**Issue by mikealbert** [CruGlobal/ansible-oracle-db-upgrade#2]
@davidhollenberger I noticed a couple scripts aren't having their output stored in a logfile or printed to the screen with debug.  Are those mostly ignorable or should we capture the data?  A couple examples below:

https://github.com/CruGlobal/ansible-oracle-db-upgrade/blob/master/tasks/upgrade.yml#L88
https://github.com/CruGlobal/ansible-oracle-db-upgrade/blob/master/tasks/upgrade.yml#L94

**Comment by mikealbert** [comment]
Here's one more:

https://github.com/CruGlobal/ansible-oracle-db-upgrade/blob/master/tasks/upgrade.yml#L133

**Comment by davidhollenberger** [comment]
post_upgrade_tasks.sql should spool the output to `oracle_stage` directory.  Not too worried out logging the output of recompiling invalid objects.  There's a check later that compares invalid objects that were not invalid before the upgrade. 

It would be worth grabbing the output of catuppst.sql and saving it.  It probably creates a log somewhere, but it may be easier to register the output then copy it to a new file.
