### ISSUE TITLE
"ORA-01034: ORACLE not available", "Process ID: 0"

### ISSUE THREAD

**Issue by SudhireV** [CruGlobal/ansible-oracle-db-upgrade#4]
Hi 
Getting following error for RAC DB, this environment didn't have ORACLE_SID etc set , all are part of 12c_1_pre_upgrade.yml file.. what am I doing different here. 

---
- hosts: oracle
  become: true
  become_user: oracle
  vars:
     db_name: TEMPDB
     accelerate: true
     oracle_user: oracle
     oracle_group: dba
     master_node: 1
     oracle_install_type: EE
     oracle_base: /u02/app/oracle
     tns_admin: /u02/app/oracle/product/11.2.0.4/TEMP/dbhome_1/network/admin
     database_parameters:
          TEMPDB:
                db_version: 12.1.0.2
                sga_target: 4G
                pga_aggregate_target: 4G
                redolog_size_mb: 4096M
                db_recovery_file_dest_size: 100G
                log_mode: archivelog
  tasks:
    - action: ping
    - name: test connection
      action: ping

  roles:
    - role: db-upgrade

changed: [10.10.112.167] => {"changed": true, "cmd": "cat db_unique_name.log", "delta": "0:00:00.025194", "end": "2017-12-14 14:24:30.563766", "invocation": {"module_args": {"_raw_params": "cat db_unique_name.log", "_uses_shell": true, "chdir": "/u03/omcs/ansible_stage/12c_upgrade/TEMPDB", "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2017-12-14 14:24:30.538572", "stderr": "", "stdout": "TEMPDB", "stdout_lines": ["TEMPDB"], "warnings": []}
changed: [10.10.112.162] => {"changed": true, "cmd": "cat db_unique_name.log", "delta": "0:00:00.015577", "end": "2017-12-14 14:24:30.811786", "invocation": {"module_args": {"_raw_params": "cat db_unique_name.log", "_uses_shell": true, "chdir": "/u03/omcs/ansible_stage/12c_upgrade/TEMPDB", "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2017-12-14 14:24:30.796209", "stderr": "", "stdout": "select trim(value) from v$parameter where name='db_unique_name'\n*\nERROR at line 1:\nORA-01034: ORACLE not available\nProcess ID: 0\nSession ID: 0 Serial number: 0", "stdout_lines": ["select trim(value) from v$parameter where name='db_unique_name'", "*", "ERROR at line 1:", "ORA-01034: ORACLE not available", "Process ID: 0", "Session ID: 0 Serial number: 0"], "warnings": []}

**Comment by SudhireV** [comment]
If I have put in TEMP1 in the instance name it's working fine for sqlplus and backups , playbook not recognising or using srvctl to poll instance information and run the commands on demand.  could be - my configuration is not correct

**Comment by SudhireV** [comment]
Updated parameter oracle_install_type: EE to oracle_instance_type: rac

Have same outcome, session not getting established, I can set oracle_home, need a way to set ORACLE_SID property, one other parameter I am not sure of is master_node , I have tried to set IP address ,, instance_id, may be any other option to be set here

**Comment by SudhireV** [comment]
added alias host_num to ansible_hosts entry.

**Comment by gopi18dba** [comment]
Hi Sudhire, I got the same issue, it is not recognizing the oracle database while doing rac upgrade.. its says idle instance.. can you please give me the whole content of alias host_num to ansible_hosts..

TASK [oradb-upgrade : Run db_unique_name.sql] ****************************************************************
fatal: [es0701vm03]: FAILED! => {"msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: {u'PATH': u'{{ oracle_home_old }}/bin:{{ oracle_home_old }}/OPatch:$PATH:/bin:/usr/bin::/usr/ccs/bin', u'ORACLE_SID': u'{{ oracle_sid }}', u'TNS_ADMIN': u'{{ tns_admin }}', u'ORACLE_BASE': u'{{ oracle_base }}', u'ORACLE_HOME': u'{{ oracle_home_old }}'}: 'tns_admin' is undefined\n\nThe error appears to have been in '/uhcdba/upgrade/ansible-oracle-db-upgrade-master/roles/oradb-upgrade/tasks/get_uniqu

**Comment by gopi18dba** [comment]
hi Sudhire, can you pls give me complete details where to add and etc host_num to ansible_host.

TASK [oradb-upgrade : Run db_unique_name.sql] ****************************************************************
fatal: [servername : FAILED! => {"msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: {u'PATH': u'{{ oracle_home_old }}/bin:{{ oracle_home_old }}/OPatch:$PATH:/bin:/usr/bin::/usr/ccs/bin', u'ORACLE_SID': u'{{ oracle_sid }}', u'TNS_ADMIN': u'{{ tns_admin }}', u'ORACLE_BASE': u'{{ oracle_base }}', u'ORACLE_HOME': u'{{ oracle_home_old }}'}: 'tns_admin' is undefined\n\nThe error appears to have been in '/uhcdba/upgrade/ansible-oracle-db-upgrade-master/roles/oradb-upgrade/tasks/get_uniqu

**Comment by gopi18dba** [comment]
oracle_sid: "{{ db_name }}{{ host_num |default('') }}" .. where we need to add this one..
